version: '3.8'

services:
  apache:
    image: php:8.1-apache
    container_name: lamp_apache
    volumes:
      - ./studenti:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenti
      MYSQL_USER: roacer
      MYSQL_PASSWORD: roacer9053
    ports:
      - "3307:3307" 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: